/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tIPI_7to4_experimental_templ.c => src/tIPI_7to4_experimental.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tIPI_7to4_experimental_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eIPIMain
 * entry port: eIPIMain
 * signature:  sIPIMain
 * context:    non-task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eIPIMain_main
 * name:         eIPIMain_main
 * global_name:  tIPI_7to4_experimental_eIPIMain_main
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
ER
eIPIMain_main(CELLIDX idx)
{
	ER		ercd = E_OK;
	CELLCB	*p_cellcb = GET_CELLCB(idx);
	(void)p_cellcb;

	/* Put statements here #_TEFB_# */
	syslog( LOG_NOTICE, "Interrup 7 to 4 occured.");
	return(ercd);
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
